### PR TITLE
Fix duplicated enum values

### PR DESCRIPTION
**Pull request by doobnet**
The value that was supposed to be a sample was not properly marked as a sample.

I recommend viewing the diff with whitespace changes off. Or looking at the commits separately.

### CODE REVIEW

**Comment by maksis** [comment]
Those values should be interpreted as samples even without an explicit marking (see the output of `ccpm_state` in https://airdcpp.docs.apiary.io/#reference/private-chat/private-chat-session/get-session).

Is your tool producing a different output? The format `property_name: sample value` is being used throughout the file.

**Comment by maksis** [comment]
The JSON schema viewed on that page also looks correct (there are no duplicate values)

**Comment by doobnet** [comment]
> Those values should be interpreted as samples even without an explicit marking (see the output of ccpm_state in https://airdcpp.docs.apiary.io/#reference/private-chat/private-chat-session/get-session).

Yeah, it looks correct airdcpp.docs.apiary.io. Hmm, perhaps I should update the version of Drafter I'm running.

> Is your tool producing a different output?

Yes, it warns about duplicated enum values. The resulting JSON file does not contain a sample section. But I haven't tested how it looks like on the site.

> The format property_name: sample value is being used throughout the file.

I know, but it seems to be a problem only with enums.

**Comment by maksis** [comment]
Seems like a similar issue has been fixed in Drafter 4.0.2: https://github.com/apiaryio/drafter/releases/tag/v4.0.2

**Comment by doobnet** [comment]
You're right. I updated to the latest version of Drafter and the warnings are gone.

**Pull request closed without merging**
